spring:
   profoles:
   active:
   - dev

---
sever:
   port: 8201
spring:
   profiles: dev
   applcation:
      name: microservicecloud-config
eureka:
   client:
      server-url:
         defaultZone: http://eureka7001.com:7001/eureka/

---
sever:
   port: 8202
spring:
   profiles: test
   applcation:
      name: microservicecloud-config
eureka:
   client:
      server-url:
         defaultZone: http://eureka7001.com:7001/eureka/
